'use client';

import { ArrowLeft, Bell, ChevronLeft, ChevronRight, LogOut, MapPin, Pencil, Save, ShieldBan, ShieldCheck, Star, X } from 'lucide-react';
import { useParams, useRouter } from 'next/navigation';
import { useCallback, useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { apiFetch } from '@/lib/api';
import { getSession } from '@/lib/auth';

type Segment = 'NEW' | 'REGULAR' | 'VIP';
type ClientDetail = { id:string; phone:string; firstName:string|null; lastName:string|null; name:string; email:string|null; avatarUrl:string|null; isActive:boolean; isBlocked:boolean; blockedAt:string|null; blockReason:string|null; lastActiveAt:string|null; createdAt:string; updatedAt:string; marketingConsent:boolean; segment:Segment; totalOrders:number; deliveredCount:number; totalSpent:number; avgCheck:number; counts:{addresses:number;reviews:number;favoriteRestaurants:number;favoriteProducts:number;devices:number;sessions:number}; piiVisible:boolean };
type Metrics = { userId:string; segment:Segment; totalOrders:number; deliveredCount:number; canceledCount:number; paidCount:number; totalSpent:number; totalPaid:number; avgCheck:number; avgPaidCheck:number; firstOrderDate:string|null; lastOrderDate:string|null; daysSinceLastOrder:number|null; tenureDays:number; ordersPerWeek:number; active7d:boolean; active30d:boolean; rates:{deliveredRatePercent:number;cancelRatePercent:number;paidRatePercent:number;reviewRatePercent:number}; reviews:{count:number;avgRating:number|null}; rfm:{recencyDays:number|null;frequency:number;monetary:number}; favoriteRestaurants:Array<{restaurantId:string;nameRu:string;nameKk:string;deliveredOrders:number}>; preferredOrderTime:{hour:number;label:string}|null; lastOrder:OrderRow|null; lastActiveAt:string|null; timeZone:string };
type OrderRow = { id:string; number:number; status:string; paymentStatus:string; paymentMethod:string; total:number; restaurantId:string; createdAt:string; updatedAt?:string; ratingGiven?:number|null; restaurant?:{id:string;nameRu:string;nameKk:string}|null };
type AddressRow = { id:string; title:string; address:string; floor:string|null; door:string|null; entrance:string|null; intercom:string|null; contactPhone:string|null; comment:string|null; createdAt:string };
type ReviewRow = { id:string; orderId:string|null; restaurantId:string; rating:number; text:string|null; isHidden:boolean; createdAt:string; restaurant?:{id:string;nameRu:string;nameKk:string}|null; order?:{id:string;number:number;status:string;total:number}|null };
type SessionRow = { id:string; platform:string; appVersion:string|null; ip:string|null; userAgent:string|null; lastUsedAt:string|null; expiresAt:string; revokedAt:string|null; revokeReason:string|null; createdAt:string; isCurrent:boolean; clientDevice?:{deviceId:string;deviceModel:string|null;osVersion:string|null;platform:string;lastSeenAt:string}|null };
type AdminShape = { roleCodes?:string[]; permissionCodes?:string[]; permissions?:string[] };

const inputClass='h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-[13px] font-semibold text-slate-900 outline-none focus:border-slate-400 focus:ring-2 focus:ring-slate-100 disabled:bg-slate-50';
function can(admin:AdminShape|null,p:string){if(!admin)return false;const roles=admin.roleCodes??[];const codes=[...(admin.permissionCodes??[]),...(admin.permissions??[])];return roles.includes('SUPER_ADMIN')||codes.includes('admin.full_access')||codes.includes(p)}
function money(v:number|null|undefined){return `${Math.round(Number(v??0)).toLocaleString('ru-RU')} ₸`}
function percent(v:number|null|undefined){return `${Number(v??0).toLocaleString('ru-RU',{maximumFractionDigits:1})}%`}
function dateTime(v:string|null|undefined){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function segmentLabel(v:Segment|undefined){return v==='VIP'?'VIP':v==='REGULAR'?'Постоянный':'Новый'}
function segmentTone(v:Segment|undefined){return v==='VIP'?'border-violet-200 bg-violet-50 text-violet-700':v==='REGULAR'?'border-blue-200 bg-blue-50 text-blue-700':'border-slate-200 bg-slate-50 text-slate-600'}
function orderStatus(v:string|null|undefined){switch(String(v??'').toUpperCase()){case'CREATED':return'Создан';case'ACCEPTED':return'Принят';case'COOKING':return'Готовится';case'READY':return'Готов';case'ON_THE_WAY':return'В пути';case'DELIVERED':return'Доставлен';case'REJECTED':return'Отклонён';case'CANCELED':return'Отменён';case'PAID':return'Оплачен';default:return'Не указан'}}
function paymentStatus(v:string|null|undefined){switch(String(v??'').toUpperCase()){case'PAID':return'Оплачено';case'PENDING':return'Ожидает оплаты';case'FAILED':return'Ошибка оплаты';case'REFUNDED':return'Возвращено';default:return'Не указано'}}
function paymentMethod(v:string|null|undefined){return String(v??'').toUpperCase()==='CASH'?'Наличные':String(v??'').toUpperCase()==='CARD'?'Карта':'Не указан'}
function platformLabel(v:string|null|undefined){const k=String(v??'').toUpperCase();return k==='ANDROID'?'Android':k==='IOS'?'iOS':k==='WEB'?'Веб':'Не определено'}
function friendlyError(error:unknown,fallback:string){if(error&&typeof error==='object'){const s=(error as {status?:unknown}).status;if(s===400)return'Проверьте заполненные данные.';if(s===401)return'Сессия истекла. Войдите снова.';if(s===403)return'У вас нет прав для этого действия.';if(s===404)return'Клиент не найден.';if(s===409)return'Эти данные уже используются.';if(typeof s==='number'&&s>=500)return'Сервис временно недоступен.'}return fallback}
function Button({children,onClick,disabled,danger=false,primary=false}:{children:ReactNode;onClick?:()=>void;disabled?:boolean;danger?:boolean;primary?:boolean}){const style=danger?'border-red-200 bg-white text-red-700 hover:bg-red-50':primary?'border-slate-950 bg-slate-950 text-white hover:bg-slate-800':'border-slate-200 bg-white text-slate-700 hover:bg-slate-50';return <button type="button" onClick={onClick} disabled={disabled} className={`inline-flex h-10 items-center justify-center gap-2 rounded-lg border px-4 text-[13px] font-bold transition disabled:cursor-not-allowed disabled:opacity-40 ${style}`}>{children}</button>}
function Kpi({label,value,note}:{label:string;value:ReactNode;note?:string}){return <div className="min-w-0 border-r border-slate-200 px-4 py-4 last:border-r-0"><div className="text-[10px] font-black uppercase tracking-[0.07em] text-slate-400">{label}</div><div className="mt-2 text-[23px] font-black tracking-[-0.03em] text-slate-950">{value}</div>{note?<div className="mt-1 text-[10px] font-medium text-slate-400">{note}</div>:null}</div>}
function Section({title,subtitle,right,children}:{title:string;subtitle?:string;right?:ReactNode;children:ReactNode}){return <section className="overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-200 px-5 py-4"><div><h2 className="text-[15px] font-black">{title}</h2>{subtitle?<p className="mt-1 text-[11px] font-medium text-slate-400">{subtitle}</p>:null}</div>{right}</div>{children}</section>}
function Info({label,value}:{label:string;value:string}){return <div className="border-b border-slate-100 pb-3 last:border-b-0 last:pb-0"><div className="text-[10px] font-bold uppercase tracking-[0.06em] text-slate-400">{label}</div><div className="mt-1 text-[13px] font-black text-slate-800">{value}</div></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-950/45 px-4"><div className="w-full max-w-[500px] rounded-xl border border-slate-200 bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h3 className="text-[17px] font-black">{title}</h3><button type="button" onClick={onClose} className="flex h-8 w-8 items-center justify-center rounded-lg border border-slate-200 text-slate-500"><X className="h-4 w-4"/></button></div><div className="p-5">{children}</div></div></div>}

export default function UserDetailsPage(){
  const {id}=useParams<{id:string}>();const router=useRouter();
  const [admin,setAdmin]=useState<AdminShape|null>(null);const [client,setClient]=useState<ClientDetail|null>(null);const [metrics,setMetrics]=useState<Metrics|null>(null);const [orders,setOrders]=useState<OrderRow[]>([]);const [ordersTotal,setOrdersTotal]=useState(0);const [ordersPage,setOrdersPage]=useState(1);const [addresses,setAddresses]=useState<AddressRow[]>([]);const [reviews,setReviews]=useState<ReviewRow[]>([]);const [sessions,setSessions]=useState<SessionRow[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);const [editing,setEditing]=useState(false);const [edit,setEdit]=useState({firstName:'',lastName:'',email:''});const [blockOpen,setBlockOpen]=useState(false);const [blockReason,setBlockReason]=useState('');const [notificationOpen,setNotificationOpen]=useState(false);const [notification,setNotification]=useState({title:'',body:''});
  const canPii=can(admin,'users.pii'),canUpdate=can(admin,'users.update'),canBlock=can(admin,'users.block'),canSessions=can(admin,'users.sessions'),canNotify=can(admin,'notifications.send');
  const loadCore=useCallback(async()=>{try{setLoading(true);setError(null);const[s,c,m]=await Promise.all([getSession(),apiFetch<ClientDetail>(`/admin/clients/${id}`),apiFetch<Metrics>(`/users/customers/${id}/metrics`)]);setAdmin((s.admin??null) as AdminShape|null);setClient(c);setMetrics(m);setEdit({firstName:c.firstName??'',lastName:c.lastName??'',email:c.email??''})}catch(e){setError(friendlyError(e,'Не удалось загрузить карточку клиента.'))}finally{setLoading(false)}},[id]);
  const loadOrders=useCallback(async()=>{try{const r=await apiFetch<{items:OrderRow[];meta:{total:number}}>(`/admin/clients/${id}/orders?page=${ordersPage}&limit=10`);setOrders(r.items??[]);setOrdersTotal(Number(r.meta?.total??0))}catch{setOrders([]);setOrdersTotal(0)}},[id,ordersPage]);
  useEffect(()=>{void loadCore()},[loadCore]);useEffect(()=>{void loadOrders()},[loadOrders]);
  useEffect(()=>{if(!admin)return;if(canPii)void apiFetch<{items:AddressRow[]}>(`/admin/clients/${id}/addresses`).then(r=>setAddresses(r.items??[])).catch(()=>setAddresses([]));if(canSessions)void apiFetch<{items:SessionRow[]}>(`/admin/clients/${id}/sessions`).then(r=>setSessions(r.items??[])).catch(()=>setSessions([]));void apiFetch<{items:ReviewRow[]}>(`/users/customers/${id}/reviews?includeOrder=1&page=1&limit=100`).then(r=>setReviews(r.items??[])).catch(()=>setReviews([]))},[admin,canPii,canSessions,id]);
  async function mutate(action:()=>Promise<unknown>,success:string){try{setBusy(true);setError(null);setNotice(null);await action();await loadCore();setNotice(success)}catch(e){setError(friendlyError(e,'Не удалось выполнить действие.'))}finally{setBusy(false)}}
  async function saveProfile(){await mutate(()=>apiFetch(`/admin/clients/${id}`,{method:'PATCH',body:JSON.stringify({firstName:edit.firstName.trim(),lastName:edit.lastName.trim(),email:edit.email.trim()||undefined})}),'Данные клиента сохранены.');setEditing(false)}
  async function blockClient(){const reason=blockReason.trim();if(reason.length<3){setError('Укажите причину блокировки.');return}setBlockOpen(false);setBlockReason('');await mutate(()=>apiFetch(`/admin/clients/${id}/block`,{method:'POST',body:JSON.stringify({reason})}),'Клиент заблокирован. Все его сеансы отозваны.')}
  async function unblockClient(){await mutate(()=>apiFetch(`/admin/clients/${id}/unblock`,{method:'POST'}),'Блокировка снята. Клиенту потребуется войти заново.')}
  async function revokeSessions(){await mutate(()=>apiFetch(`/admin/clients/${id}/sessions/revoke`,{method:'POST'}),'Все активные сеансы клиента завершены.');if(canSessions){const r=await apiFetch<{items:SessionRow[]}>(`/admin/clients/${id}/sessions`).catch(()=>({items:[]}));setSessions(r.items??[])}}
  async function sendNotification(){const title=notification.title.trim(),body=notification.body.trim();if(title.length<2||body.length<2){setError('Укажите заголовок и текст уведомления.');return}setNotificationOpen(false);await mutate(()=>apiFetch('/admin/notifications/campaigns',{method:'POST',body:JSON.stringify({title,body,targetType:'USER_IDS',targetUserIds:[id]})}),'Уведомление поставлено в очередь отправки.');setNotification({title:'',body:''})}
  const pages=Math.max(1,Math.ceil(ordersTotal/10));const activeSessions=sessions.filter(s=>s.isCurrent).length;
  if(loading&&!client)return <main className="min-h-screen bg-[#f7f7f8] p-6"><div className="h-44 animate-pulse rounded-lg border border-slate-200 bg-white"/></main>;
  return <main className="min-h-screen bg-[#f7f7f8] px-5 py-6 text-slate-950 sm:px-6 lg:px-8"><div className="w-full space-y-4">
    <header className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-3"><button type="button" onClick={()=>router.push('/layout-20/users')} className="flex h-10 w-10 items-center justify-center rounded-lg border border-slate-200 bg-white text-slate-600"><ArrowLeft className="h-4 w-4"/></button><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-[27px] font-black tracking-[-0.03em]">{client?.name||'Клиент'}</h1><span className={`rounded-md border px-2 py-1 text-[11px] font-bold ${segmentTone(metrics?.segment??client?.segment)}`}>{segmentLabel(metrics?.segment??client?.segment)}</span>{client?.isBlocked?<span className="rounded-md border border-red-200 bg-red-50 px-2 py-1 text-[11px] font-bold text-red-700">Заблокирован</span>:<span className="rounded-md border border-emerald-200 bg-emerald-50 px-2 py-1 text-[11px] font-bold text-emerald-700">Активен</span>}</div><p className="mt-1 text-[12px] font-medium text-slate-400">Регистрация {dateTime(client?.createdAt)} · последняя активность {dateTime(client?.lastActiveAt)}</p></div></div><div className="flex flex-wrap gap-2">{canNotify&&<Button onClick={()=>setNotificationOpen(true)}><Bell className="h-4 w-4"/>Уведомление</Button>}{canSessions&&<Button onClick={()=>void revokeSessions()} disabled={busy||activeSessions===0}><LogOut className="h-4 w-4"/>Завершить сеансы</Button>}{canBlock&&(client?.isBlocked?<Button onClick={()=>void unblockClient()} disabled={busy}><ShieldCheck className="h-4 w-4"/>Разблокировать</Button>:<Button danger onClick={()=>setBlockOpen(true)} disabled={busy}><ShieldBan className="h-4 w-4"/>Заблокировать</Button>)}</div></header>
    {error&&<div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-[13px] font-semibold text-red-700">{error}</div>}{notice&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-[13px] font-semibold text-emerald-700">{notice}</div>}{client?.isBlocked&&client.blockReason&&<div className="rounded-lg border border-red-200 bg-white px-4 py-3 text-[12px] text-slate-600"><b className="text-red-700">Причина блокировки:</b> {client.blockReason}</div>}
    <section className="overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8"><Kpi label="Заказы" value={metrics?.totalOrders??client?.totalOrders??0} note={`доставлено ${metrics?.deliveredCount??client?.deliveredCount??0}`}/><Kpi label="Потрачено" value={money(metrics?.totalSpent??client?.totalSpent)} note="доставленные"/><Kpi label="Средний чек" value={money(metrics?.avgCheck??client?.avgCheck)}/><Kpi label="Оплачено" value={metrics?.paidCount??0} note={money(metrics?.totalPaid)}/><Kpi label="Отмены" value={metrics?.canceledCount??0} note={percent(metrics?.rates.cancelRatePercent)}/><Kpi label="Отзывы" value={metrics?.reviews.count??client?.counts.reviews??0} note={metrics?.reviews.avgRating==null?'нет оценки':`${metrics.reviews.avgRating.toFixed(1)} из 5`}/><Kpi label="Частота" value={metrics?.ordersPerWeek??0} note="доставок/нед."/><Kpi label="С последнего" value={metrics?.daysSinceLastOrder??'—'} note="дней"/></div></section>
    <div className="grid gap-4 xl:grid-cols-[360px_1fr]"><div className="space-y-4"><Section title="Данные клиента" right={canUpdate?<Button onClick={()=>setEditing(v=>!v)}><Pencil className="h-4 w-4"/>{editing?'Отмена':'Изменить'}</Button>:undefined}><div className="space-y-3 p-5">{editing?<><label className="block"><span className="mb-1 block text-[11px] font-bold text-slate-500">Имя</span><input className={inputClass} value={edit.firstName} onChange={e=>setEdit({...edit,firstName:e.target.value})}/></label><label className="block"><span className="mb-1 block text-[11px] font-bold text-slate-500">Фамилия</span><input className={inputClass} value={edit.lastName} onChange={e=>setEdit({...edit,lastName:e.target.value})}/></label><label className="block"><span className="mb-1 block text-[11px] font-bold text-slate-500">Почта</span><input className={inputClass} value={edit.email} onChange={e=>setEdit({...edit,email:e.target.value})}/></label><Button primary onClick={()=>void saveProfile()} disabled={busy}><Save className="h-4 w-4"/>Сохранить</Button></>:<><Info label="Телефон" value={client?.phone||'—'}/><Info label="Почта" value={client?.email||'Не указана'}/><Info label="Сегмент" value={`${segmentLabel(metrics?.segment??client?.segment)} · по доставленным заказам`}/><Info label="Маркетинговые сообщения" value={client?.marketingConsent?'Разрешены':'Не разрешены'}/><Info label="Активен за 7 дней" value={metrics?.active7d?'Да':'Нет'}/><Info label="Активен за 30 дней" value={metrics?.active30d?'Да':'Нет'}/></>}</div></Section><Section title="Предпочтения" subtitle="Только по доставленным заказам"><div className="divide-y divide-slate-100"><div className="px-5 py-3.5"><div className="text-[11px] font-bold text-slate-400">Чаще заказывает</div><div className="mt-1 text-[13px] font-black">{metrics?.preferredOrderTime?.label??'Недостаточно данных'}</div></div>{(metrics?.favoriteRestaurants??[]).length?metrics!.favoriteRestaurants.map(x=><div key={x.restaurantId} className="px-5 py-3.5"><div className="text-[12px] font-black">{x.nameRu}</div><div className="mt-1 text-[10px] text-slate-400">{x.deliveredOrders} доставленных заказов</div></div>):<div className="px-5 py-4 text-[12px] text-slate-400">Любимые рестораны ещё не определены.</div>}</div></Section></div>
      <div className="space-y-4"><Section title="История заказов" subtitle={`${ordersTotal} заказов`} right={<div className="flex gap-2"><Button onClick={()=>setOrdersPage(v=>Math.max(1,v-1))} disabled={ordersPage<=1}><ChevronLeft className="h-4 w-4"/></Button><Button onClick={()=>setOrdersPage(v=>v+1)} disabled={ordersPage>=pages}><ChevronRight className="h-4 w-4"/></Button></div>}><div className="overflow-x-auto"><table className="min-w-[760px] w-full"><thead><tr className="border-b border-slate-200 bg-slate-50 text-left text-[10px] font-black uppercase text-slate-400"><th className="px-4 py-3">Заказ</th><th className="px-4 py-3">Ресторан</th><th className="px-4 py-3">Статус</th><th className="px-4 py-3">Оплата</th><th className="px-4 py-3 text-right">Сумма</th><th className="px-4 py-3">Дата</th></tr></thead><tbody>{orders.length?orders.map(o=><tr key={o.id} onClick={()=>router.push(`/layout-20/orders/${o.id}`)} className="cursor-pointer border-b border-slate-100 text-[12px] font-semibold hover:bg-slate-50"><td className="px-4 py-3.5 font-black">№{o.number}</td><td className="px-4 py-3.5">{o.restaurant?.nameRu||'—'}</td><td className="px-4 py-3.5">{orderStatus(o.status)}</td><td className="px-4 py-3.5">{paymentStatus(o.paymentStatus)} · {paymentMethod(o.paymentMethod)}</td><td className="px-4 py-3.5 text-right font-black">{money(o.total)}</td><td className="px-4 py-3.5 text-slate-500">{dateTime(o.createdAt)}</td></tr>):<tr><td colSpan={6} className="px-4 py-10 text-center text-[12px] text-slate-400">Заказов нет.</td></tr>}</tbody></table></div></Section><Section title="RFM" subtitle="Фактические показатели без искусственного рейтинга"><div className="grid grid-cols-3 divide-x divide-slate-200"><Kpi label="Давность" value={metrics?.rfm.recencyDays??'—'} note="дней с доставки"/><Kpi label="Частота" value={metrics?.rfm.frequency??0} note="доставок"/><Kpi label="Сумма" value={money(metrics?.rfm.monetary)} note="доставленные"/></div></Section></div></div>
    <div className="grid gap-4 xl:grid-cols-2"><Section title="Адреса" subtitle={canPii?`${addresses.length} сохранённых`:'Нужен доступ к персональным данным'}>{canPii?<div className="divide-y divide-slate-100">{addresses.length?addresses.map(a=><div key={a.id} className="px-5 py-4"><div className="flex gap-3"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-slate-400"/><div><div className="text-[12px] font-black">{a.title||'Адрес'}</div><div className="mt-1 text-[12px] text-slate-600">{a.address}</div><div className="mt-1 text-[10px] text-slate-400">{[a.entrance&&`подъезд ${a.entrance}`,a.floor&&`этаж ${a.floor}`,a.door&&`дверь ${a.door}`].filter(Boolean).join(' · ')||'Дополнительных данных нет'}</div>{a.comment?<div className="mt-2 text-[11px] text-slate-500">Комментарий: {a.comment}</div>:null}</div></div></div>):<div className="px-5 py-8 text-center text-[12px] text-slate-400">Адресов нет.</div>}</div>:<div className="px-5 py-8 text-center text-[12px] text-slate-400">Адреса скрыты согласно вашим правам.</div>}</Section><Section title="Отзывы" subtitle={`${reviews.length} загружено`}><div className="divide-y divide-slate-100">{reviews.length?reviews.map(r=><div key={r.id} className="px-5 py-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-1 text-[12px] font-black"><Star className="h-4 w-4 fill-amber-400 text-amber-400"/>{r.rating}/5 · {r.restaurant?.nameRu||'Ресторан'}</div><div className="text-[10px] text-slate-400">{dateTime(r.createdAt)}</div></div>{r.text?<p className="mt-2 text-[12px] leading-5 text-slate-600">{r.text}</p>:<p className="mt-2 text-[11px] text-slate-400">Без комментария</p>}{r.order?.number?<button type="button" className="mt-2 text-[11px] font-bold underline" onClick={()=>router.push(`/layout-20/orders/${r.order!.id}`)}>Заказ №{r.order.number}</button>:null}{r.isHidden?<div className="mt-2 text-[10px] font-bold text-red-600">Скрыт модерацией</div>:null}</div>):<div className="px-5 py-8 text-center text-[12px] text-slate-400">Отзывов нет.</div>}</div></Section></div>
    {canSessions&&<Section title="Сеансы и устройства" subtitle={`${activeSessions} активных сеансов`}><div className="overflow-x-auto"><table className="min-w-[760px] w-full"><thead><tr className="border-b border-slate-200 bg-slate-50 text-left text-[10px] font-black uppercase text-slate-400"><th className="px-4 py-3">Устройство</th><th className="px-4 py-3">Приложение</th><th className="px-4 py-3">Последняя активность</th><th className="px-4 py-3">Состояние</th><th className="px-4 py-3">Создан</th></tr></thead><tbody>{sessions.length?sessions.map(s=><tr key={s.id} className="border-b border-slate-100 text-[12px] font-semibold"><td className="px-4 py-3.5"><b>{platformLabel(s.clientDevice?.platform||s.platform)}</b><div className="mt-1 text-[10px] text-slate-400">{s.clientDevice?.deviceModel||'Модель не указана'}{s.clientDevice?.osVersion?` · ${s.clientDevice.osVersion}`:''}</div></td><td className="px-4 py-3.5">{s.appVersion||'—'}</td><td className="px-4 py-3.5">{dateTime(s.lastUsedAt)}</td><td className="px-4 py-3.5"><span className={`rounded-md border px-2 py-1 text-[10px] font-bold ${s.isCurrent?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-slate-200 bg-slate-50 text-slate-500'}`}>{s.isCurrent?'Активен':'Завершён'}</span></td><td className="px-4 py-3.5">{dateTime(s.createdAt)}</td></tr>):<tr><td colSpan={5} className="px-4 py-10 text-center text-[12px] text-slate-400">Сеансов нет.</td></tr>}</tbody></table></div></Section>}
  </div>{blockOpen&&<Modal title="Заблокировать клиента" onClose={()=>setBlockOpen(false)}><p className="mb-3 text-[12px] leading-5 text-slate-500">Все активные сеансы будут завершены, новые входы запрещены.</p><textarea value={blockReason} onChange={e=>setBlockReason(e.target.value)} rows={4} placeholder="Причина блокировки" className="w-full rounded-lg border border-slate-200 p-3 text-[13px] font-semibold outline-none"/><div className="mt-4 flex justify-end gap-2"><Button onClick={()=>setBlockOpen(false)}>Отмена</Button><Button danger onClick={()=>void blockClient()} disabled={busy}>Заблокировать</Button></div></Modal>}{notificationOpen&&<Modal title="Уведомление клиенту" onClose={()=>setNotificationOpen(false)}><div className="space-y-3"><label className="block"><span className="mb-1 block text-[11px] font-bold text-slate-500">Заголовок</span><input className={inputClass} value={notification.title} onChange={e=>setNotification({...notification,title:e.target.value})}/></label><label className="block"><span className="mb-1 block text-[11px] font-bold text-slate-500">Текст</span><textarea rows={5} value={notification.body} onChange={e=>setNotification({...notification,body:e.target.value})} className="w-full rounded-lg border border-slate-200 p-3 text-[13px] font-semibold outline-none"/></label></div><div className="mt-4 flex justify-end gap-2"><Button onClick={()=>setNotificationOpen(false)}>Отмена</Button><Button primary onClick={()=>void sendNotification()} disabled={busy}>Отправить</Button></div></Modal>}</main>
}
